# Generated by Django 5.0.6 on 2024-05-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['order_number']},
        ),
    ]
