# Generated by Django 5.0.6 on 2024-05-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_alter_achievement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='authors',
            field=models.ManyToManyField(to='applicants.author'),
        ),
    ]
